DROP SCHEMA IF EXISTS dmi;
DROP USER IF EXISTS dmi_owner;
CREATE USER dmi_owner WITH PASSWORD 'secret';
CREATE SCHEMA dmi AUTHORIZATION dmi_owner;

DROP USER IF EXISTS dmi_read;
CREATE USER dmi_read WITH PASSWORD 'secret';
GRANT USAGE ON SCHEMA dmi TO dmi_read;
GRANT SELECT ON ALL TABLES IN SCHEMA dmi TO dmi_read;
